<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL 基本网站链接
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
| CodeIgniter根URL。通常,这将是你的基URL,末尾斜杠:
|	http://example.com/
|
| If this is not set then CodeIgniter will try guess the protocol, domain
| and path to your installation. However, you should always configure this
| explicitly and never rely on auto-guessing, especially in production
| environments.
| 如果没有设置CodeIgniter会猜出协议,域和路径安装。然而,您应该总是显式配置这个,从不依靠auto-guessing,尤其是在生产环境中。
*/
$config['base_url'] = '';

/*
|--------------------------------------------------------------------------
| Index File  索引文件
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
| 通常,这将是你的索引.php文件,除非你重新命名为别的东西。如果您使用的是mod_rewrite删除页面设置此变量是空白。
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL URI协议
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
| 这个项目确定哪些服务器全球应该用于检索URI字符串。默认设置的“REQUEST_URI”在大多数服务器工作。如果你的链接似乎并不工作,试试另一个美味的口味:
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
| 警告:如果您设置这个“PATH_INFO”,总是会uri URL-decoded !
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix  URL后缀
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
| 这个选项允许您添加一个后缀CodeIgniter的url生成。有关更多信息,请参阅用户指南:
| http://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language  默认语言
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
| 这个决定应该使用语言的文件集。确保有一个可用的翻译如果你打算使用除英语之外的其他东西。
*/
$config['language']	= 'chinese';
//$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set 默认字符集设置
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
| 这决定了哪些默认字符集使用各种方法,需要提供一个字符集。
| See参见 http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks 开启/关闭 系统钩子
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
| 如果你想使用的“钩子”功能,你必须使它将这个变量设置为TRUE(布尔)。有关详细信息,请参阅用户指南。
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix 类扩展前缀
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
| 这个项目允许你设置文件名/名称前缀当扩展本地库。有关更多信息,请参阅用户指南:
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading 设计者自动加载
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
| 启用该设置将告诉CodeIgniter寻找一个作曲家包应用程序/供应商/ autoload.php装载器脚本。
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
| 或者如果你有供应商/目录位于其他地方,你可以选择一个特定的路径设置为:
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
| 关于作曲家的更多信息
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
| 注意:这不会禁用或覆盖CodeIgniter-specific |半自动的
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters 允许URL字符
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
| 这允许您指定字符被允许在您的url。当有人试图提交URL字符不允许他们会得到一个警告信息。
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
| 作为一项安全措施你强烈建议限制的url尽可能几个字符。默认情况下只允许这些:a - z 0 - 9 ~ %:_ -
| Leave blank to allow all characters -- but only if you are insane.
| 留下空白,让所有的人物——但只有如果你是疯了。
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
| 配置的价值实际上是一个正则表达式字符组和它将执行:!preg_match(' / ^[< permitted_uri_chars >]+ $ /i
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
| 不要改变这个,除非你完全理解影响! !
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings  启用查询字符串
|--------------------------------------------------------------------------
| 默认情况下CodeIgniter使用搜索引擎友好段基础url:
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
| 默认情况下CodeIgniter允许访问$ _GET数组。如果由于某种原因你想禁用它,“allow_get_array”设置为FALSE。
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
| 您可以选择性地启用标准基础url查询字符串:
| Options are: TRUE or FALSE (boolean) 选项有:真或假(布尔)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
| 其他物品让你设置查询字符串“单词”,将调用控制器及其功能:
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
| 请注意,一些帮手无法正常工作时启用了这个功能,因为CodeIgniter主要是为了使用基于段的url。
*/
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Error Logging Threshold  错误日志阈值
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
| 您可以启用错误日志通过设置一个阈值在0。阈值确定记录什么。阈值的选择是:
|	0 = Disables logging, Error logging TURNED OFF  禁用日志记录错误日志关闭
|	1 = Error Messages (including PHP errors) 错误消息(包括PHP错误)
|	2 = Debug Messages 调试消息 
|	3 = Informational Messages  信息消息 
|	4 = All Messages 所有消息 
|
| You can also pass an array with threshold levels to show individual error types
| 你也可以通过数组与阈值水平显示个人的错误类型
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
| 直播网站你通常只会让错误(1)否则你记录的日志文件将很快填满。
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path 错误日志目录路径
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
| 离开这个空白,除非你想设置默认的应用程序/ logs /目录以外的东西。使用一个完整的服务器路径末尾斜杠。
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension 日志文件扩展名
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
| 默认的日志文件的文件扩展名。默认的php允许保护日志文件通过基本的脚本,当它们被存储在一个公开访问的目录中。
| Note: Leaving it blank will default to 'php'.
| 注意:让它空白将默认的php。
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions 日志文件的权限
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
| 文件系统权限应用在新创建的日志文件。
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal integer notation (i.e. 0700, 0644, etc.)
|  重要:这一定是一个整数(没有引号),您必须使用八进制整数符号          
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs 日期格式的日志
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
| 记录每一项都有一个关联的日期。您可以使用PHP代码来设置自己的日期格式
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path 错误观点目录路径
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
| 离开这个空白,除非你想设置不是默认应用程序/视图/错误/目录。使用一个完整的服务器路径末尾斜杠。
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path 缓存目录路径
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
| 离开这个空白,除非你想设置不是默认应用程序/缓存/目录。使用一个完整的服务器路径末尾斜杠
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String 缓存包含查询字符串
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
| 是否考虑URL查询字符串在生成输出缓存文件。有效的选项是:
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account. 启用时,考虑所有查询参数。
|	             Please be aware that this may result in numerous cache 请注意,这可能会导致大量的缓存
|	             files generated for the same page over and over again. 文件为同一页面生成一遍又一遍。
|	array('q') = Enabled, but only take into account the specified list 启用,但只考虑指定的列表
|	             of query parameters. 查询参数
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key 加密钥匙
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
| 如果你使用加密类,您必须设置一个加密密钥。更多信息查看用户指南。
| http://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables 会话变量
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|   存储驱动程序使用方法:文件、数据库、复述,memcached
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|   会话cookie的名称,必须只包含[0-9a-z_ -)字符
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last. 你想让会话的秒数。
|	Setting to 0 (zero) means expire when the browser is closed.
|   设置为0(零)意味着当浏览器关闭到期。
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|   位置保存会话,驱动的依赖。
|	For the 'files' driver, it's a path to a writable directory. “文件”的driver,这是一个可写目录路径。
|	WARNING: Only absolute paths are supported! 警告:仅支持绝对路径!
|
|	For the 'database' driver, it's a table name. 对于数据库的驱动程序,它是一个表名。
|	Please read up the manual for the format with other session drivers.
|   请阅读手册的格式与其他会话的驱动。
|	IMPORTANT: You are REQUIRED to set a valid save path!
|   重要:您必须设置一个有效的保存路径!
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|   是否匹配用户的IP地址读会话数据。
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|   警告:如果您正在使用的数据库驱动程序,别忘了更新您的会话表的主键,当改变这个设置。
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|   多少秒CI再生之间的会话ID。
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|   是否破坏与旧会话ID相关联的会话数据当auto-regenerating会话ID。当设置为FALSE时,数据将被垃圾收集器后删除。
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|   其他会话cookie设置共享与应用程序的其余部分,除了‘cookie_prefix’和‘cookie_httponly’,它将被忽略。
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables  cookie相关变量
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions 如果你需要设置cookie名称前缀避免碰撞
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies 设置为.your-domain.com站点范围内的cookie
| 'cookie_path'     = Typically will be a forward slash  通常将是一个斜杠
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists. Cookie只设置一个安全的HTTPS连接的存在。
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript) 饼干只能通过HTTP(S)(没有javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|  注意:这些设置(除了“cookie_prefix”和“cookie_httponly”)也会影响会话。
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines 标准化换行
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data, 决定是否在输入数据标准化换行字符,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value. 意义取代\ r \ n \ r \ n与PHP_EOL值出现
|
| This is particularly useful for portability between UNIX-based OSes, 这是特别有用的基于unix的操作系统之间的可移植性,
| (usually \n) and Windows (\r\n). (通常\ n)和Windows(\ r \ n)。
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering 全局XSS过滤
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
| XSS过滤器决定时总是积极,遇到或COOKIE数据
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
| 警告:此功能是弃用,目前只有向后兼容的目的!
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery 跨站点请求伪装
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
| 使CSRF饼干令牌设置。设置为TRUE时,令牌将检查提交的表单。如果你是接受用户数据,强烈建议CSRF保护被启用。
| 'csrf_token_name' = The token name 令牌名称
| 'csrf_cookie_name' = The cookie name cookie的名称
| 'csrf_expire' = The number in seconds the token should expire. 令牌的秒数应该到期
| 'csrf_regenerate' = Regenerate token on every submission 在每个提交重新生成令牌
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks 数组的uri忽略CSRF检查
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression 输出压缩
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| 启用Gzip压缩输出页面加载速度更快。当启用时,输出类将测试您的服务器是否支持Gzip。
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
| 即使是这样,然而,并不是所有的浏览器都支持压缩使只有如果你确信你的访客可以处理它。
| Only used if zlib.output_compression is turned off in your php.ini. 如果zlib只用。在你的php . ini output_compression是关闭的。
| Please do not use it together with httpd-level output compression. 请不要使用它一起httpd-level输出压缩。
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
| 非常重要的:如果你得到一个空白页面启用压缩时,这意味着你过早地输出到浏览器。它甚至可以一行空格结束时你的一个脚本。
| 对于压缩工作,没有什么可以发送输出缓冲区之前由输出类调用。不启用了压缩“回声”任何值。
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference 掌握时间参考
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
| 选择“本地”或任何PHP支持时区。这种偏好告诉系统是否使用你的当地时间服务器的主现在的参考,或把它配置一个时区。看到“日期助手”页面用户指南的信息处理。
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags 重写PHP短标签
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
| 如果PHP安装没有短标签支持启用CI可以重写标签动态,使您能够利用语法在你的视图文件。选择是对还是错(布尔)
| Note: You need to have eval() enabled for this to work.
| 注意:您需要eval()支持这一工作。
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs 反向代理ip
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
| 如果你的服务器是在反向代理,你必须的代理IP地址白名单CodeIgniter应该相信头如HTTP_X_FORWARDED_FOR和HTTP_CLIENT_IP为了正确识别访问者的IP地址
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
| 您可以使用一个数组或一个以逗号分隔的代理地址,以及指定子网。下面是一些例子:
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';
